-- +goose Up
-- Создание таблицы Product
CREATE TABLE IF NOT EXISTS PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETEDAT TIMESTAMP NULL,
    LABEL VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL UNIQUE,
    SKU VARCHAR(255) NOT NULL UNIQUE,
    PRICE DECIMAL(15,2) NOT NULL,
    QUANTITY INT NOT NULL,
    ISVISIBLE BOOLEAN NOT NULL DEFAULT TRUE,
    CATEGORYID INT NOT NULL,
    CONSTRAINT fk_product_category 
        FOREIGN KEY (CATEGORYID)
        REFERENCES CATEGORY(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    STATUSID INT NOT NULL,
    CONSTRAINT fk_product_status 
        FOREIGN KEY (STATUSID)
        REFERENCES ENUMERATIONVALUE(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_product_code ON PRODUCT(CODE);
CREATE INDEX idx_product_sku ON PRODUCT(SKU);

-- +goose Down
DROP TABLE IF EXISTS PRODUCT;
