-- +goose Up
-- Создание таблицы PERSON
CREATE TABLE PERSON (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETEDAT TIMESTAMP NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL UNIQUE,
    USERLOGIN VARCHAR(255) NOT NULL UNIQUE
);

CREATE INDEX idx_person_userid ON PERSON(USERLOGIN);

-- +goose Down
DROP TABLE IF EXISTS PERSON;
