-- +goose Up
-- Создание таблицы Category
CREATE TABLE CATEGORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LABEL VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL UNIQUE,
    CATEGORYID INT,
    CONSTRAINT fk_parent_category 
        FOREIGN KEY (CATEGORYID)
        REFERENCES CATEGORY(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_caregory_code ON CATEGORY(CODE);

-- +goose Down
DROP TABLE IF EXISTS CATEGORY;
