-- +goose Up
-- Создание таблицы ORDER
CREATE TABLE IF NOT EXISTS ORDERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DETAILS TEXT,
    STATUSID INT NOT NULL,
    CONSTRAINT fk_order_status 
        FOREIGN KEY (STATUSID)
        REFERENCES ENUMERATIONVALUE(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CLIENTID INT NOT NULL,
    CONSTRAINT fk_order_client 
        FOREIGN KEY (CLIENTID)
        REFERENCES PERSON(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    MANAGERID INT,
    CONSTRAINT fk_order_manager 
        FOREIGN KEY (CLIENTID)
        REFERENCES PERSON(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_order_clientid ON ORDERS(CLIENTID);
CREATE INDEX idx_order_statusid ON ORDERS(STATUSID);
CREATE INDEX idx_order_managerid_statusid ON ORDERS(MANAGERID, STATUSID);

-- +goose Down
DROP TABLE IF EXISTS ORDERS;