-- +goose Up
-- Создание таблицы CART
CREATE TABLE IF NOT EXISTS CART (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PERSONID INT NOT NULL,
    CONSTRAINT fk_cart_person 
        FOREIGN KEY (PERSONID)
        REFERENCES PERSON(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_cart_personid ON CART(PERSONID);

-- +goose Down
DROP TABLE IF EXISTS CART;
