-- +goose Up
-- Создание таблицы ENUMERATION
CREATE TABLE IF NOT EXISTS ENUMERATION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CODE VARCHAR(255) NOT NULL UNIQUE,
    LABEL VARCHAR(255) NOT NULL
);

CREATE INDEX ix_enumeration_code ON ENUMERATION(CODE);

-- +goose Down
DROP TABLE IF EXISTS ENUMERATION;