-- +goose Up
-- Создание таблицы ENUMERATION
CREATE TABLE ENUMERATION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CODE VARCHAR(255) NOT NULL UNIQUE,
    LABEL VARCHAR(255) NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS ENUMERATION;