-- +goose Up
-- Создание таблицы CARTITEM
CREATE TABLE IF NOT EXISTS CARTITEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    QUANTITY INT NOT NULL,
    CARTID INT NOT NULL,
    CONSTRAINT fk_cart_item_cart 
        FOREIGN KEY (CARTID)
        REFERENCES CART(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    PRODUCTID INT NOT NULL,
    CONSTRAINT fk_cart_item_product 
        FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_cart_item_cart_id_product_id ON CARTITEM(CARTID, PRODUCTID);

-- +goose Down
DROP TABLE IF EXISTS CARTITEM;
