-- +goose Up
-- Создание таблицы PRODUCTMEDIA
CREATE TABLE IF NOT EXISTS PRODUCTMEDIA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LINK VARCHAR(255) NOT NULL,
    PRODUCTID INT NOT NULL,
    CONSTRAINT fk_productmedia_product 
        FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_productmedia_product ON PRODUCTMEDIA(PRODUCTID);

-- +goose Down
DROP TABLE IF EXISTS PRODUCTMEDIA;
