-- +goose Up
-- Создание таблицы ENUMERATIONVALUE
CREATE TABLE ENUMERATIONVALUE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CODE VARCHAR(255) NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    ENUMERATIONID INT NOT NULL,
    CONSTRAINT fk_enumerationvalue_enumeration 
        FOREIGN KEY (ENUMERATIONID) 
        REFERENCES ENUMERATION(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_enumerationvalue_enumerationid ON ENUMERATIONVALUE(ENUMERATIONID);

-- +goose Down
DROP TABLE IF EXISTS ENUMERATIONVALUE;
