-- +goose Up
-- Создание таблицы ORDERITEM
CREATE TABLE IF NOT EXISTS ORDERITEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    STATUSID INT NOT NULL,
    CONSTRAINT fk_order_item_status 
        FOREIGN KEY (STATUSID)
        REFERENCES ENUMERATIONVALUE(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    ORDERID INT NOT NULL,
    CONSTRAINT fk_order_item_order 
        FOREIGN KEY (ORDERID)
        REFERENCES ORDERS(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CARTITEMID INT NOT NULL,
    CONSTRAINT fk_order_item_cart_item 
        FOREIGN KEY (CARTITEMID)
        REFERENCES CARTITEM(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_order_item_orderid ON ORDERITEM(ORDERID);

-- +goose Down
DROP TABLE IF EXISTS ORDERITEM;