-- +goose Up
-- Создание таблицы USER_
CREATE TABLE USER_ (
    ID BIGINT PRIMARY KEY DEFAULT (NEXT VALUE FOR entity_id_seq),
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETEDAT TIMESTAMP NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    STATUSID INT NOT NULL,
    CONSTRAINT fk_user_status 
        FOREIGN KEY (STATUSID) 
        REFERENCES ENUMERATIONVALUE(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX idx_user_statusid ON USER_(STATUSID);

-- +goose Down
DROP TABLE IF EXISTS USER_;
