-- +goose Up
-- Создание таблицы ROLE
CREATE TABLE ROLE_USER (
    ID BIGINT PRIMARY KEY DEFAULT (NEXT VALUE FOR entity_id_seq),
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ROLEID INT NOT NULL,
    CONSTRAINT fk_role_user 
        FOREIGN KEY (ROLEID) 
        REFERENCES ROLE_(ID)
        ON DELETE CASCADE,
    USERID INT NOT NULL UNIQUE,
    CONSTRAINT fk_user_role 
        FOREIGN KEY (USERID) 
        REFERENCES USER_(ID)
        ON DELETE CASCADE
);

CREATE INDEX idx_role_user ON ROLE_USER(USERID, ROLEID);

-- +goose Down
DROP TABLE IF EXISTS ROLE_USER;
