-- +goose Up
-- Создание таблицы ROLE
CREATE TABLE ROLE_ (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LABEL VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL UNIQUE
);

CREATE INDEX idx_user_code ON ROLE_(CODE);

-- +goose Down
DROP TABLE IF EXISTS ROLE_;
